nohup ./farPPD macros/Scoring_macro_0.mac &>test0.log &
nohup ./farPPD macros/Scoring_macro_5.mac &>test5.log &
nohup ./farPPD macros/Scoring_macro_10.mac &>test10.log &
nohup ./farPPD macros/Scoring_macro_15.mac &>test15.log &
nohup ./farPPD macros/Scoring_macro_20.mac &>test20.log &
nohup ./farPPD macros/Scoring_macro_25.mac &>test25.log &
nohup ./farPPD macros/Scoring_macro_30.mac &>test30.log &
nohup ./farPPD macros/Scoring_macro_35.mac &>test35.log &
nohup ./farPPD macros/Scoring_macro_40.mac &>test40.log &
nohup ./farPPD macros/Scoring_macro_45.mac &>test45.log &
nohup ./farPPD macros/Scoring_macro_50.mac &>test50.log &
nohup ./farPPD macros/Scoring_macro_55.mac &>test55.log &
nohup ./farPPD macros/Scoring_macro_60.mac &>test60.log &
nohup ./farPPD macros/Scoring_macro_65.mac &>test65.log &
nohup ./farPPD macros/Scoring_macro_70.mac &>test70.log &
nohup ./farPPD macros/Scoring_macro_75.mac &>test75.log &
nohup ./farPPD macros/Scoring_macro_80.mac &>test80.log &
nohup ./farPPD macros/Scoring_macro_85.mac &>test85.log &
nohup ./farPPD macros/Scoring_macro_90.mac &>test90.log &
nohup ./farPPD macros/Scoring_macro_95.mac &>test95.log &
nohup ./farPPD macros/Scoring_macro_100.mac &>test100.log &
nohup ./farPPD macros/Scoring_macro_105.mac &>test105.log &
nohup ./farPPD macros/Scoring_macro_110.mac &>test110.log &
nohup ./farPPD macros/Scoring_macro_115.mac &>test115.log &
nohup ./farPPD macros/Scoring_macro_120.mac &>test120.log &
nohup ./farPPD macros/Scoring_macro_125.mac &>test125.log &
nohup ./farPPD macros/Scoring_macro_130.mac &>test130.log &
nohup ./farPPD macros/Scoring_macro_135.mac &>test135.log &
nohup ./farPPD macros/Scoring_macro_140.mac &>test140.log &
nohup ./farPPD macros/Scoring_macro_145.mac &>test145.log &
nohup ./farPPD macros/Scoring_macro_150.mac &>test150.log &
nohup ./farPPD macros/Scoring_macro_155.mac &>test155.log &
nohup ./farPPD macros/Scoring_macro_160.mac &>test160.log &
nohup ./farPPD macros/Scoring_macro_165.mac &>test165.log &
nohup ./farPPD macros/Scoring_macro_170.mac &>test170.log &
nohup ./farPPD macros/Scoring_macro_175.mac &>test175.log &
nohup ./farPPD macros/Scoring_macro_180.mac &>test180.log &
nohup ./farPPD macros/Scoring_macro_185.mac &>test185.log &
nohup ./farPPD macros/Scoring_macro_190.mac &>test190.log &
nohup ./farPPD macros/Scoring_macro_195.mac &>test195.log &
nohup ./farPPD macros/Scoring_macro_200.mac &>test200.log &
